### ISSUE TITLE
SummerRouter重复注册问题

### ISSUE THREAD

**Issue by noddle0592** [yale8848/Summer#17]
JDK Version:  1.8.51
LIB Version: 1.1.8 
---

SummerRouter类的registerResource方法里头的classInfos这个list为类变量，每次新注册的时候会导致原来的list被重复注册一次
另外MethodsProcessor里面的newClass方法调用的是无参的构造方法，觉得可以加上一个Vertx类的构造方法，如果有就优先构造这个一个参数的方法。这样方便在Handler中使用

**Comment by yale8848** [comment]
ok，收到

**Comment by yale8848** [comment]
1.1.9 重复注册的问题已经修改，至于添加Vertx参数构造函数我觉得暂时不需要，直接@Context Vertx vertx 注入就好了；
